{
 "title": "Data Availability Read",
 "description": "Subsystem and test environment metrics",
 "tags": [
  "subsystem",
  "benchmark"
 ],
 "time": { "from": "2023-11-28T13:05:32.794Z", "to": "2023-11-28T13:06:56.173Z" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Source of data", "query": "prometheus" },
   { "name": "cpu_group_by", "label": "Group CPU usage", "query": "task_name, task_group" }
  ]
 },
 "panels": [
  {
   "title": "Test configuration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "subsystem_benchmark_n_validators{}",
     "legendFormat": "n_validators"
    },
    { "expr": "subsystem_benchmark_n_cores{}", "legendFormat": "n_cores" }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All tasks CPU usage breakdown",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "repeat": "nodename",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(bizinikiwi_tasks_polling_duration_sum{}[2s])) by ($cpu_group_by)",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Availability subsystem CPU usage per block",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(bizinikiwi_tasks_polling_duration_sum{task_group=\"availability-recovery\"}[6s])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Total CPU burn",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(bizinikiwi_tasks_polling_duration_sum{}) by ($cpu_group_by)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "All candidates in block recovery time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "subsystem_benchmark_block_time", "legendFormat": "Instant block time" }
   ]
  },
  {
   "title": "Emulated network throughput ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(subsystem_benchmark_network_peer_total_bytes_received{}[5s]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(subsystem_benchmark_network_peer_total_bytes_sent{}[5s]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Emulated peer throughput",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(subsystem_benchmark_network_peer_total_bytes_received{}[10s])",
     "legendFormat": "Received by {{peer}}"
    },
    {
     "expr": "rate(subsystem_benchmark_network_peer_total_bytes_sent{}[10s])",
     "legendFormat": "Sent by {{peer}}"
    }
   ]
  },
  {
   "title": "Recovered PoV sizes",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(subsystem_benchmark_pov_size_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Number of erasure-encoded chunks of data belonging to candidate blocks. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "chunks/s" } },
   "targets": [
    {
     "expr": "sum(rate(pezkuwi_teyrchain_availability_recovery_chunk_requests_issued{}[10s]))",
     "legendFormat": "Chunks requested"
    }
   ]
  },
  {
   "title": "Availability subsystem metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time to recover a PoV",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(increase(pezkuwi_teyrchain_availability_recovery_time_total_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Chunk request duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum(increase(pezkuwi_teyrchain_availability_recovery_time_chunk_request_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Recovery throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pezkuwi_teyrchain_availability_recovery_bytes_total{}[30s])",
     "legendFormat": "Bytes recovered"
    }
   ]
  },
  {
   "title": "Re-encoding chunks timing",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sum(increase(pezkuwi_teyrchain_availability_reencode_chunks_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Erasure recovery (no I/O)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "sum(increase(pezkuwi_teyrchain_availability_recovery_time_erasure_recovery_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Recoveries",
   "type": "timeseries",
   "description": "Number of erasure-encoded chunks of data belonging to candidate blocks. ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pezkuwi_teyrchain_availability_recovery_recoveries_finished{}[1s]))",
     "legendFormat": "Finished"
    },
    {
     "expr": "sum(rate(pezkuwi_teyrchain_availability_recovery_recovieries_started{}[1s]))",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Approval voting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {}
   ]
  }
 ]
}