{
 "title": "Bizinikiwi Service Tasks with bizinikiwi prefix",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU time spent on each task",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(bizinikiwi_tasks_polling_duration_sum{}[$__rate_interval])) by (task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Task polling rate per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "rate(bizinikiwi_tasks_polling_duration_count{}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Average time it takes to call Future::poll()",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(bizinikiwi_tasks_polling_duration_sum{}[$__rate_interval]) / increase(bizinikiwi_tasks_polling_duration_count{}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks started",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bizinikiwi_tasks_spawned_total{}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of tasks running",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bizinikiwi_tasks_spawned_total{} - sum(bizinikiwi_tasks_ended_total{}) without(reason)\n\n# Fallback if tasks_ended_total is null for that task\nor on(task_name) bizinikiwi_tasks_spawned_total{}",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of calls to `Future::poll` that took more than one second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "repeat": "nodename",
   "yaxes": [
    { "format": "cps", "label": "Calls to `Future::poll`/second" }
   ],
   "targets": [
    {
     "expr": "irate(bizinikiwi_tasks_polling_duration_bucket{le=\"+Inf\"}[$__rate_interval])\n    - ignoring(le)\n  irate(bizinikiwi_tasks_polling_duration_bucket{le=\"1.024\"}[$__rate_interval]) > 0",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Unbounded Channels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  }
 ]
}