// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pezpallet_tnpos`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE BIZINIKIWI BENCHMARK CLI VERSION 32.0.1
//! DATE: 2026-10-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `vmi3628515`, CPU: `AMD EPYC Processor (with IBPB)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// pezframe-omni-bencher
// v1
// benchmark
// pezpallet
// --extrinsic=*
// --runtime=target/production/wbuild/people-zagros-runtime/people_zagros_runtime.wasm
// --pezpallet=pezpallet_tnpos
// --header=/home/runner/actions-runner/_work/pezkuwi-DKS/pezkuwi-DKS/pezcumulus/file_header.txt
// --output=./pezcumulus/teyrchains/runtimes/people/people-zagros/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=20
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use pezframe_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pezpallet_tnpos`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: pezframe_system::Config> pezpallet_tnpos::WeightInfo for WeightInfo<T> {
	/// Storage: `Tnpos::Banned` (r:1 w:0)
	/// Proof: `Tnpos::Banned` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:9 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::RelayKeys` (r:1 w:0)
	/// Proof: `Tnpos::RelayKeys` (`max_values`: None, `max_size`: Some(562), added: 3037, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::BondedOnAssetHub` (r:1 w:0)
	/// Proof: `Tnpos::BondedOnAssetHub` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::InPoolSince` (r:0 w:1)
	/// Proof: `Tnpos::InPoolSince` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn join() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `285`
		//  Estimated: `34255`
		// Minimum execution time: 60_582_000 picoseconds.
		Weight::from_parts(96_673_000, 0)
			.saturating_add(Weight::from_parts(0, 34255))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:1 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::InPoolSince` (r:0 w:1)
	/// Proof: `Tnpos::InPoolSince` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `3514`
		// Minimum execution time: 23_691_000 picoseconds.
		Weight::from_parts(38_091_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Tnpos::PoolMembers` (r:1 w:0)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::EraStart` (r:1 w:0)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SeedCommitments` (r:1 w:1)
	/// Proof: `Tnpos::SeedCommitments` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn commit_seed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234`
		//  Estimated: `3557`
		// Minimum execution time: 22_530_000 picoseconds.
		Weight::from_parts(37_351_000, 0)
			.saturating_add(Weight::from_parts(0, 3557))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Tnpos::EraStart` (r:1 w:0)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SeedCommitments` (r:1 w:1)
	/// Proof: `Tnpos::SeedCommitments` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::NextSeed` (r:1 w:1)
	/// Proof: `Tnpos::NextSeed` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn reveal_seed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `314`
		//  Estimated: `3557`
		// Minimum execution time: 21_381_000 picoseconds.
		Weight::from_parts(35_611_000, 0)
			.saturating_add(Weight::from_parts(0, 3557))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Tnpos::Strata` (r:1 w:0)
	/// Proof: `Tnpos::Strata` (`max_values`: Some(1), `max_size`: Some(145), added: 640, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::BondedOnAssetHub` (r:1 w:0)
	/// Proof: `Tnpos::BondedOnAssetHub` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::PoolMembers` (r:1001 w:0)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::RelayKeys` (r:1000 w:0)
	/// Proof: `Tnpos::RelayKeys` (`max_values`: None, `max_size`: Some(562), added: 3037, mode: `MaxEncodedLen`)
	/// Storage: `StakingScore::CachedStakingDetails` (r:224 w:0)
	/// Proof: `StakingScore::CachedStakingDetails` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `StakingScore::StakingStartBlock` (r:112 w:0)
	/// Proof: `StakingScore::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `StakingScore::StakeFirstSeen` (r:112 w:0)
	/// Proof: `StakingScore::StakeFirstSeen` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Welati::ParliamentMembers` (r:1 w:0)
	/// Proof: `Welati::ParliamentMembers` (`max_values`: Some(1), `max_size`: Some(11057), added: 11552, mode: `MaxEncodedLen`)
	/// Storage: `Welati::DiwanMembers` (r:1 w:0)
	/// Proof: `Welati::DiwanMembers` (`max_values`: Some(1), `max_size`: Some(804), added: 1299, mode: `MaxEncodedLen`)
	/// Storage: `Perwerde::PerwerdeScores` (r:111 w:0)
	/// Proof: `Perwerde::PerwerdeScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Tiki::UserTikis` (r:111 w:0)
	/// Proof: `Tiki::UserTikis` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Tiki::TikiExpiry` (r:111 w:0)
	/// Proof: `Tiki::TikiExpiry` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Trust::TrustScores` (r:243 w:0)
	/// Proof: `Trust::TrustScores` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `Welati::AttestedRegion` (r:111 w:0)
	/// Proof: `Welati::AttestedRegion` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SeatedSessions` (r:111 w:0)
	/// Proof: `Tnpos::SeatedSessions` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::Banned` (r:111 w:0)
	/// Proof: `Tnpos::Banned` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SessionsObserved` (r:1 w:0)
	/// Proof: `Tnpos::SessionsObserved` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CoFailures` (r:111 w:0)
	/// Proof: `Tnpos::CoFailures` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:1)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::NextSeed` (r:1 w:1)
	/// Proof: `Tnpos::NextSeed` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
	/// Proof: `TeyrchainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PezkuwiXcm::SupportedVersion` (r:2 w:0)
	/// Proof: `PezkuwiXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TeyrchainSystem::HostConfiguration` (r:1 w:0)
	/// Proof: `TeyrchainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:0)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `TeyrchainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::EraStart` (r:0 w:1)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentCommittee` (r:0 w:1)
	/// Proof: `Tnpos::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(2050), added: 2545, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[450, 1000]`.
	fn seat_committee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `36749 + p * (212 ±0)`
		//  Estimated: `128790 + p * (3037 ±0)`
		// Minimum execution time: 26_398_278_000 picoseconds.
		Weight::from_parts(33_285_425_000, 0)
			.saturating_add(Weight::from_parts(0, 128790))
			// Standard Error: 921_434
			.saturating_add(Weight::from_parts(58_562_136, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(35))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 3037).saturating_mul(p.into()))
	}
	/// Storage: `Tnpos::BondedOnAssetHub` (r:1 w:1)
	/// Proof: `Tnpos::BondedOnAssetHub` (`max_values`: Some(1), `max_size`: Some(32770), added: 33265, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::BondReportEra` (r:1 w:1)
	/// Proof: `Tnpos::BondReportEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 1024]`.
	fn note_bonded(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `117`
		//  Estimated: `34255`
		// Minimum execution time: 19_750_000 picoseconds.
		Weight::from_parts(28_026_510, 0)
			.saturating_add(Weight::from_parts(0, 34255))
			// Standard Error: 663
			.saturating_add(Weight::from_parts(187_864, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Diwan::Members` (r:1 w:0)
	/// Proof: `Diwan::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::Strata` (r:0 w:1)
	/// Proof: `Tnpos::Strata` (`max_values`: Some(1), `max_size`: Some(145), added: 640, mode: `MaxEncodedLen`)
	fn set_strata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 12_711_000 picoseconds.
		Weight::from_parts(22_461_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Diwan::Members` (r:1 w:0)
	/// Proof: `Diwan::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:1 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentCommittee` (r:1 w:1)
	/// Proof: `Tnpos::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(2050), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::Banned` (r:1 w:1)
	/// Proof: `Tnpos::Banned` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Trust::TrustScores` (r:26 w:0)
	/// Proof: `Trust::TrustScores` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
	/// Proof: `TeyrchainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PezkuwiXcm::SupportedVersion` (r:2 w:0)
	/// Proof: `PezkuwiXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TeyrchainSystem::HostConfiguration` (r:1 w:0)
	/// Proof: `TeyrchainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `XcmpQueue::DeliveryFeeFactor` (r:1 w:0)
	/// Proof: `XcmpQueue::DeliveryFeeFactor` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `XcmpQueue::OutboundXcmpStatus` (r:1 w:0)
	/// Proof: `XcmpQueue::OutboundXcmpStatus` (`max_values`: Some(1), `max_size`: Some(2306), added: 2801, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::RelevantMessagingState` (r:1 w:0)
	/// Proof: `TeyrchainSystem::RelevantMessagingState` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::InPoolSince` (r:0 w:1)
	/// Proof: `Tnpos::InPoolSince` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn report_offence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9006`
		//  Estimated: `67004`
		// Minimum execution time: 462_365_000 picoseconds.
		Weight::from_parts(671_611_000, 0)
			.saturating_add(Weight::from_parts(0, 67004))
			.saturating_add(T::DbWeight::get().reads(39))
			.saturating_add(T::DbWeight::get().writes(5))
	}
}
