// Copyright (C) Parity Technologies (UK) Ltd. and Dijital Kurdistan Tech Institute
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Weights for `pezpallet_parameters` on this chain.
//!
//! NOT AUTOGENERATED, and that is the point of this comment. The number below is the Asset
//! Hub's measured figure for the same call, taken on the reference machine on 2026-08-28:
//! `set_parameter` is one read and one write of one storage item, and the two runtimes run it
//! on the same hardware. It is here so the extrinsic is not free -- a zero weight is a free
//! call and a free call is a free block -- and it is a placeholder, not a measurement of this
//! chain. `pezpallet_parameters` is in this runtime's `define_benchmarks!` list, so the next
//! benchmarking pass overwrites this file with a real one and this header goes with it.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use pezframe_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pezpallet_parameters`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: pezframe_system::Config> pezpallet_parameters::WeightInfo for WeightInfo<T> {
	/// Storage: `Parameters::Parameters` (r:1 w:1)
	/// Proof: `Parameters::Parameters` (`max_values`: None, `max_size`: Some(11322), added:
	/// 13797, mode: `MaxEncodedLen`)
	fn set_parameter() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `14787`
		// Minimum execution time: 5_884_000 picoseconds.
		Weight::from_parts(6_204_000, 14787)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}
