// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for `pezpallet_tnpos`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE BIZINIKIWI BENCHMARK CLI VERSION 32.0.1
//! DATE: 2026-08-30, STEPS: `50`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `vmi3519825`, CPU: `AMD EPYC Processor (with IBPB)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// pezframe-omni-bencher
// v1
// benchmark
// pezpallet
// --extrinsic=*
// --runtime=target/production/wbuild/people-pezkuwichain-runtime/people_pezkuwichain_runtime.wasm
// --pezpallet=pezpallet_tnpos
// --header=/opt/actions-runner/_work/pezkuwi-DKS/pezkuwi-DKS/pezcumulus/file_header.txt
// --output=./pezcumulus/teyrchains/runtimes/people/people-pezkuwichain/src/weights
// --wasm-execution=compiled
// --steps=50
// --repeat=100
// --heap-pages=4096
// --no-storage-info
// --no-min-squares
// --no-median-slopes

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use pezframe_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pezpallet_tnpos`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: pezframe_system::Config> pezpallet_tnpos::WeightInfo for WeightInfo<T> {
	/// Storage: `Tnpos::Banned` (r:1 w:0)
	/// Proof: `Tnpos::Banned` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:9 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::RelayKeys` (r:1 w:0)
	/// Proof: `Tnpos::RelayKeys` (`max_values`: None, `max_size`: Some(562), added: 3037, mode: `MaxEncodedLen`)
	/// Storage: `Trust::TrustScores` (r:1 w:0)
	/// Proof: `Trust::TrustScores` (`max_values`: None, `max_size`: Some(64), added: 2539, mode: `MaxEncodedLen`)
	fn join() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `332`
		//  Estimated: `23382`
		// Minimum execution time: 58_278_000 picoseconds.
		Weight::from_parts(91_680_000, 0)
			.saturating_add(Weight::from_parts(0, 23382))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:1 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	fn leave() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3514`
		// Minimum execution time: 21_299_000 picoseconds.
		Weight::from_parts(34_895_000, 0)
			.saturating_add(Weight::from_parts(0, 3514))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Tnpos::PoolMembers` (r:1 w:0)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::EraStart` (r:1 w:0)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SeedCommitments` (r:1 w:1)
	/// Proof: `Tnpos::SeedCommitments` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	fn commit_seed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3557`
		// Minimum execution time: 21_238_000 picoseconds.
		Weight::from_parts(33_994_000, 0)
			.saturating_add(Weight::from_parts(0, 3557))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Tnpos::EraStart` (r:1 w:0)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::SeedCommitments` (r:1 w:1)
	/// Proof: `Tnpos::SeedCommitments` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::NextSeed` (r:1 w:1)
	/// Proof: `Tnpos::NextSeed` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	fn reveal_seed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281`
		//  Estimated: `3557`
		// Minimum execution time: 20_187_000 picoseconds.
		Weight::from_parts(32_511_000, 0)
			.saturating_add(Weight::from_parts(0, 3557))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Tnpos::Strata` (r:1 w:0)
	/// Proof: `Tnpos::Strata` (`max_values`: Some(1), `max_size`: Some(145), added: 640, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:9 w:0)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:1)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::PoolMembers` (r:1001 w:0)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::RelayKeys` (r:1000 w:0)
	/// Proof: `Tnpos::RelayKeys` (`max_values`: None, `max_size`: Some(562), added: 3037, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::NextSeed` (r:1 w:1)
	/// Proof: `Tnpos::NextSeed` (`max_values`: Some(1), `max_size`: Some(36), added: 531, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
	/// Proof: `TeyrchainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PezkuwiXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PezkuwiXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TeyrchainSystem::HostConfiguration` (r:1 w:0)
	/// Proof: `TeyrchainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::EraStart` (r:0 w:1)
	/// Proof: `Tnpos::EraStart` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentCommittee` (r:0 w:1)
	/// Proof: `Tnpos::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(2050), added: 2545, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[450, 1000]`.
	fn seat_committee(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `953 + p * (139 ±0)`
		//  Estimated: `23382 + p * (3037 ±0)`
		// Minimum execution time: 17_184_860_000 picoseconds.
		Weight::from_parts(21_477_222_000, 0)
			.saturating_add(Weight::from_parts(0, 23382))
			// Standard Error: 361_934
			.saturating_add(Weight::from_parts(40_734_666, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(Weight::from_parts(0, 3037).saturating_mul(p.into()))
	}
	/// Storage: `Diwan::Members` (r:1 w:0)
	/// Proof: `Diwan::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::Strata` (r:0 w:1)
	/// Proof: `Tnpos::Strata` (`max_values`: Some(1), `max_size`: Some(145), added: 640, mode: `MaxEncodedLen`)
	fn set_strata() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1489`
		// Minimum execution time: 12_563_000 picoseconds.
		Weight::from_parts(22_602_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Diwan::Members` (r:1 w:0)
	/// Proof: `Diwan::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Tnpos::PoolMembers` (r:1 w:1)
	/// Proof: `Tnpos::PoolMembers` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::StratumSize` (r:1 w:1)
	/// Proof: `Tnpos::StratumSize` (`max_values`: None, `max_size`: Some(13), added: 2488, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentCommittee` (r:1 w:1)
	/// Proof: `Tnpos::CurrentCommittee` (`max_values`: Some(1), `max_size`: Some(2050), added: 2545, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::CurrentEra` (r:1 w:0)
	/// Proof: `Tnpos::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Tnpos::Banned` (r:1 w:1)
	/// Proof: `Tnpos::Banned` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `TeyrchainSystem::UpwardDeliveryFeeFactor` (r:1 w:0)
	/// Proof: `TeyrchainSystem::UpwardDeliveryFeeFactor` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `PezkuwiXcm::SupportedVersion` (r:1 w:0)
	/// Proof: `PezkuwiXcm::SupportedVersion` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TeyrchainSystem::HostConfiguration` (r:1 w:0)
	/// Proof: `TeyrchainSystem::HostConfiguration` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn report_offence() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2291`
		//  Estimated: `5756`
		// Minimum execution time: 187_359_000 picoseconds.
		Weight::from_parts(270_684_000, 0)
			.saturating_add(Weight::from_parts(0, 5756))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
